# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc3b0900529e9196e265e2589cf89caed735d499eeddf84875eb95c090e0c25688bfd2dcae97f57c00217132202600da3d744b9cbe1c64726e2e8df7f5e61d80

test:
  secret_key_base: f872552595edeb20ee3bfd59789d289644ddda375bd9edd62a412022ce208df76ac7cb32f31bcfd78a04a1230fbfcc3e2e31d0f911cfa9ebadd8665bfba5665b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
